version: '3.3'

networks:
  caddy:
    name: caddy
    external: true
services:
  evolution_api:
    container_name: evolution_api
    image: atendai/evolution-api:v1.8.2
    restart: always
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    environment:
      # Configura o evolution-api para ler as variáveis de ambiente
      - SERVER_URL=https://api.dominio.com
      - DOCKER_ENV=true
      - DEL_INSTANCE=false
      - AUTHENTICATION_JWT_EXPIRIN_IN=0
      # Define a porta no qual o evolution-api vai rodar
      - SERVER_PORT=8080
      # Configura o Nível de Log
      - LOG_LEVEL=ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK
      # Configura o evolution-api para autenticar como API Key
      - AUTHENTICATION_TYPE=apikey
      # Define a API Key Global
      - AUTHENTICATION_API_KEY=XXXXXX
      # Habilita os Webhooks
      - WEBHOOK_GLOBAL_ENABLED=false
      # Define o endereço do Webhook
      - WEBHOOK_GLOBAL_URL=https://webhook.dominio.com/webhook
      # Configura o dispositibo
      - CONFIG_SESSION_PHONE_CLIENT='Evolution API'
      - CONFIG_SESSION_PHONE_NAME=Chrome
      # Habilita o Redis para armazenar a sessão
      - REDIS_ENABLED=false
      # Define o caminho do Redis
      - REDIS_URI=redis://redis/1
      - REDIS_PREFIX_KEY=evolution
      # Exponer info sobre instancia
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      # RAabbitMQ Config
      - RABBITMQ_ENABLED=true
      - RABBITMQ_URI=amqp://user:pass@rabbitmq:5672/default
      - RABBITMQ_EXCHANGE_NAME=evolution_exchange
    command: ['node', './dist/src/main.js']
    labels:
      caddy: api.dominio.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - caddy

volumes:
  evolution_instances:
  evolution_store: